Added colour and copyright notice

diff --git a/ffvacuum b/ffvacuum
--- a/ffvacuum
+++ b/ffvacuum
@@ -1,7 +1,37 @@
 #!/bin/bash
 
+# Copyright 2009  Michiel van Wessem, Manchester, United Kingdom
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions are
+# met:
+#
+# * Redistributions of source code must retain the above copyright
+# notice, this list of conditions and the following disclaimer.
+#
+# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
+# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
+# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
+# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
+# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
+# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
+# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
+# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
+# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
+# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+
 # based on http://www.gettingclever.com/2008/06/vacuum-your-firefox-3.html
 
+# 
+verbose=${verbose:-YES}
+
+# set some bold/bright ANSI colours
+red="\033[01;31m"
+green="\033[01;32m"
+blue="\033[01;34m"
+normal="\033[00m"
 # Make sure sqlite3 is installed on the system.
 if [ ! -x $(which sqlite3) ]; then
     echo "sqlite3 not found or non executable..."
@@ -21,9 +51,16 @@ fi
     ( cd ${profiles}
       echo "${profiles} --"
       for database in *.sqlite; do
-        echo "  Vacuuming ${database}..."
-        echo "VACUUM;" | sqlite3 ${database} 
-       done
+        printf "%12s %-54s" Vaccuuming ${database}...
+        echo "VACUUM;" | sqlite3 ${database}
+        
+        status=$?
+        if [[ ${status} -eq 0 ]]; then
+          echo -e "${blue}[ ${green}cleaned${blue} ]${normal}"
+        else
+          echo -e "${blue}[ ${red}failed${blue} ]${normal}"
+        fi
+      done
     )
   done
 )
